name: Deploy build from homologDev to main

on:
  push:
    branches: [homologDev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório completo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para mudar de branch

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Trocar para a branch main e substituir com dist
        run: |
          git checkout main

          # Limpa tudo da main exceto o .git
          find . -maxdepth 1 ! -name '.git' ! -name '.' -exec rm -rf {} +

          # Copia arquivos da dist para a raiz da main
          cp -r dist/* ./
          rm -rf dist

          git add .
          git commit -m "Deploy automático da homologDev via GitHub Actions" || echo "Nada para commitar"
          git push origin main
